Modified SqlContext so that it extends WayangContext and provides a new constructor, refs #378
apache/incubator-wayang pull request #379
Opened 2023-11-21 10:43 UTC by juripetersen

2023-11-21 10:52 UTC, kbeedkar requested changes
Please remove IDE-specific (hidden) files.

2023-11-21 10:55 UTC, juripetersen commented
> Please remove IDE-specific (hidden) files.

@kbeedkar I removed them in the last two commits. The changes tab only shows modifications in `SqlContext` for me. 
Can you see other changes that I forgot to remove?

2023-11-21 11:04 UTC, kbeedkar approved these changes

2023-11-22 03:20 UTC, merged

2023-11-22 03:20 UTC, kbeedkar commented
Thanks for your contributions @juripetersen