Add all plugins to MultiContextDeserializer
apache/incubator-wayang pull request #457
Opened 2024-08-06 13:20 UTC by Aryant01

I've added two new plugins: Hadoop and GraphChi, and I've also uncommented a previously mentioned plugin. Since I'm new to open source, please let me know if I've missed anything.

2024-08-08 09:47 UTC, zkaoudi requested changes
Hi,

we don't have a hadoop and graphchi plugin. Also please double check before doing any PR that all tests pass. This is very important.

2024-08-08 09:48 UTC, zkaoudi commented
Also, the headers are mandatory to all files so you should not have removed it :)

2024-08-08 13:32 UTC, Aryant01 commented
Hi, I apologize for my impatience. I'll make sure to address the bugs and mistakes I've introduced, and I'll be more mindful of testing in the future. Thank you for your patience and assistance.

2024-08-08 13:40 UTC, 2pk03 commented
Hey @Aryant01,

Great to see you here! 

We know it's overwhelming to start working on open source projects, we've all been there! That's why we've put together information to make it easier to contribute => https://wayang.apache.org/docs/community/contribute

We also encourage contributors (yes, you're one now 👍🏾) to join the public mailing lists => https://wayang.apache.org/docs/community/mailinglist.

Keep up the great work and thank you,
 @2pk03

2024-08-08 15:29 UTC, Aryant01 commented
Hey @2pk03 ,
Thankyou for your concern. I really appreciate it. I will follow the contribution guide and will be joining the mailing lists.
Thankyou.

2024-08-22 07:18 UTC, zkaoudi commented
Hi @Aryant01, thank you for your question. I believe it's missing some implementation so that Flink works with the multicontext. Could you try uncommenting that line and check if everything runs correctly?

2025-03-27 07:18 UTC, juripetersen commented
@zkaoudi @Aryant01 @2pk03 This PR seems to be stale, we should either update or close it.

2025-03-27 07:20 UTC, zkaoudi commented
Yes let's close it

2025-03-27 07:21 UTC, closed without merging